### ISSUE TITLE
Date+Time and Now Playing widgets

### ISSUE THREAD

**Issue by elmugrat** [felixhageloh/uebersicht-widgets#119]
Hi, I've made a couple of clean widgets:

https://github.com/elmugrat/uebersicht_nowplaying

https://github.com/elmugrat/uebersicht_datetime

Thanks for the work on Übersicht!

**Comment by felixhageloh** [comment]
Hi and sorry for the late reply! Things were a little slow over the holidays :). 
Thanks for submitting your widgets; they look great! Since there are already widgets doing basically the same thing in the widgets gallery, we usually ask people if they would consider submitting their improvements as a pull request to the original widgets. This is to keep the widgets gallery concise and focused and basically to use the power of github to keep improving existing widgets. Hope you understand!
