### ISSUE TITLE
iStats Widget and RVM

### ISSUE THREAD

**Issue by thesp0nge** [felixhageloh/uebersicht-widgets#218]
Using RVM on a OSX, I installed iStats gem under the global gems for my 2.2.2 ruby interpreter.

I installed the widget and changed the command this way

```
,command: '/Users/thesp0nge/.rvm/rubies/ruby-2.2.2/bin/ruby /Users/thesp0nge/.rvm/gems/ruby-2.2.2/bin/istats'
```

The widget returned the following error
```
/Users/thesp0nge/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- sparkr (LoadError)
	from /Users/thesp0nge/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/thesp0nge/.rvm/gems/ruby-2.2.2/gems/iStats-1.2.0/lib/iStats.rb:6:in `
```

**Comment by felixhageloh** [comment]
pinging the author of the widget: @roele any ideas?

**Comment by roele** [comment]
@thesp0nge As i'm not the author of iStats if have to refer you to https://github.com/Chris911/iStats.

**Comment by felixhageloh** [comment]
thanks sorry about that !

**Comment by thesp0nge** [comment]
The problem is that iStats works well inside an RVM, but changing the ruby invocation in JS file, it seems this one doesn't honour the RVM environment

**Comment by roele** [comment]
@thesp0nge Reading https://github.com/rvm/rvm you should probably use something like `rvm -e istats`

**Comment by thesp0nge** [comment]
Doesn't work.
```
rvm -e istats
unknown action 'ruby'
```

How Übersicht, spawn the shell to execute command?


On 2 February 2016 at 23:47, Roland Schaer <notifications@github.com> wrote:

> @thesp0nge <https://github.com/thesp0nge> Reading
> https://github.com/rvm/rvm you should probably use something like rvm -e
> istats
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/felixhageloh/uebersicht-widgets/issues/218#issuecomment-178872092>
> .
>



-- 
$ cd /pub
$ more beer

I pirati della sicurezza applicativa: https://codiceinsicuro.it

**Comment by roele** [comment]
@thesp0nge Due to incompatibilities with older OSX versions i will change the command to use an external shell script of the following nature.

```
#!/usr/bin/env bash

#
# Executes iStats command
# 

if test $(which iStats); then

    # define command
    command=( "$(which iStats)" )

    # execute
    "${command[@]}"

fi
```

Can you check if this possibly solves your issue with RVM as well? 
(Just put the script as istats.sh inside the istats.widget folder (with 0755) and change the command to `istats.widget/istats.sh`)

**Comment by thesp0nge** [comment]
Putting in the istats.widget it doesn't work since the path has a space "/Library/Application Support/Übersicht/widgets/istats.widget" and even escaping it doesn't work, it was returning command not found.

I moved the shell script to my ~/bin dir and the error changed: <div id="istats-widget-index-js" class="widget">undefined is not an object (evaluating 'data.fan')</div>

**Comment by roele** [comment]
@thesp0nge Pushed a [fix](https://github.com/roele/istats.widget/issues/5) for Yosemite compatability which also includes a fix for the error you mentioned. Give it a try and let me know if it works with RVM. If not i'd suggest you open an issue in https://github.com/roele/istats.widget with all the details (OSX Version, RVM version, installations paths etc.) and i'll have a closer look.

@felixhageloh May i ask you to close this issue here? Thanks!
