### ISSUE TITLE
The clunker: my sidebar widget

### ISSUE THREAD

**Issue by Pe8er** [felixhageloh/uebersicht-widgets#224]
It's mostly a mish-mash of functionalities borrowed from other widgets (did my best to give credit where due) + a few bits I managed to put together, such as flex positioning and easy background blur.

For your health: https://github.com/Pe8er/uWidgets-Distribution/tree/master/Sidebar

**Comment by felixhageloh** [comment]
great, thanks - it's been added via your repo! 
Btw check out your screenshot size - it gets a bit squashed at the moment

**Comment by Pe8er** [comment]
Hey F!

I'm sorry to bother you. I decided to split my widgets into separate repositories, seeing you recommend it to another user. Here they are:

[Playbox](https://github.com/Pe8er/Playbox.Widget)

[Sidebar](https://github.com/Pe8er/Sidebar.Widget)

**Comment by felixhageloh** [comment]
Hey Piotr!
no worries! I'm actually OK with your extra repo since it has been well behaved so far :). I only don't want to add any new repos like that because I realized that it was getting a bit hard to maintain (making sure that there are no duplicate widgets etc). 

Having said that, I'll probably migrate your widgets this weekend just to make things more consistent. So it was only those two?

**Comment by Pe8er** [comment]
Yes, these two for now. I promise I'll make more!! :)

**Comment by felixhageloh** [comment]
:) Just making sure - I somehow remembered there were more. 
I've migrated them!
