### ISSUE TITLE
An extremely simple date of today widget that is sort of a fuzzy time companion

### ISSUE THREAD

**Issue by ruurd** [felixhageloh/uebersicht-widgets#234]
An extremely simple date of today widget that is sort of a fuzzy time companion.
Basically I took fuzzytime and just display the date of today on the right hand side of the desktop.

https://github.com/ruurd/simpledate

**Comment by soberstadt** [comment]
How does this widget differ from the existing https://github.com/soberstadt/simple-clock-widget and https://github.com/felixhageloh/uebersicht-widgets/tree/master/SimpleDate widgets? Is there anything special that we could work to merge into one of those widgets? We are trying to avoid adding duplicates to the widget gallery (not a perfect system, but we're working on it).

**Comment by ruurd** [comment]
Ehm no other than that it is really really barebones. To get to the point this widget is you probably need to remove a lot of other stuff from the two mentioned and in terms of style it follows fyzzy date almost to the pixel.

**Comment by soberstadt** [comment]
Ok, I think I'm going to close this now because I think your widget is really similar to existing ones. If you would like to add a setting to either my widget or @ SpencerKaiser's simpledate, please let us know. Thanks for sharing what you made!

**Comment by ruurd** [comment]
I think I disagree. To cross the divide from the widgets you mention to the extremely simple thing I made to match fuzzy clock is quite a bit of work. Adding a setting to the other widgets would be odd. Why push code into it that changes a lot of the styling and a lot of the functionality of the other two widgets to arrive at a much simpler widget?

**Comment by soberstadt** [comment]
@felixhageloh any thoughts?

**Comment by ruurd** [comment]
Maybe it could be 'marketed' as a fyzzy-time-date-companion???

**Comment by soberstadt** [comment]
Then what if we added the date as a setting to the time on @plan8studios's widget? Similar to how its a setting on simple-clock.

**Comment by ruurd** [comment]
If they would allow that... The same argument holds though: if you want fuzzy time but not a date what is the better solution? Turn it of/strip it out or just have a separate widget? Additional point, the date widget does not nearly need the refresh frequency the date widget needs. 

However you have a good point in saying that the styling is similar. It is.

**Comment by soberstadt** [comment]
We may have to wait for @felixhageloh or @plan8studios to share his thoughts, but I prefer adding configuration to existing widgets over adding new ones. But those are only might opinion.

**Comment by ruurd** [comment]
My preference would be exactly the opposite: make a widget do one thing and one thing only. A possible way of extending Übersicht would be common styling perhaps and I think an improvement would maybe be timed events like every top of the minute and top of the hour and top of the day to facilitate calendars and clocks and the like.

**Comment by plan8studios** [comment]
I'm with @ruurd in thinking that a widget should do one thing. I also like the idea of common styling and timed events.

**Comment by felixhageloh** [comment]
my main concern was/is that I wouldn't want to add widgets to the gallery that do the same as existing widgets with just some (minor) styling differences. Especially if they are literally just a copy of the code with some style changes. That's when we would ask people to make the new styling an option/theme for an existing widget. 

Being a bit more idealistic, sometimes we/I took it even further and ask people to add their changes to existing widgets even if the change was a bit more than just styling. Basically if it seemed like a small iteration over the same thing, like showing the time as HH:MM:SS or just as HH:MM - and maybe showing the date next to it or not. 

I feel like that approach has proven to be difficult, mostly because it is very vague were to draw the line, and because of situations like this. As @soberstadt mentioned, its not a perfect system, but we're working on it :). So I feel like the best approach is really just to avoid the 'copy widget' -> 'change styling' -> 'submit new widget' scenario and be lenient in other cases.

So it that light I'm for adding this widget. I'm actually really surprised there is no widget that just shows the date in numbers yet, but it really is the case :)
