### ISSUE TITLE
Modified TimeInWords to TimeInWrds

### ISSUE THREAD

**Issue by mactexan** [felixhageloh/uebersicht-widgets#257]
Not sure this would count as a separate widget, but I dressed up the original time in words widget to display a more Mac-like theme by replacing all the letter "o" with the character "" (and a few more tweaks, mostly font and shading).  https://github.com/mactexan/timeinw-rds

**Comment by felixhageloh** [comment]
Once again, thanks :). I am a bit reluctant to add this one to the gallery, since I try to avoid widgets that are re-styled iterations of existing ones. In these cases I usually recommend contacting the author of the original widget first to see if they are open to add your style to their widget (using an option to activate it, for example)
