### ISSUE TITLE
LED Clock Widget

### ISSUE THREAD

**Issue by imranzahid01** [felixhageloh/uebersicht-widgets#302]
Hi,

I created a new LED Digital Clock widget, hope you can add it to your repo

[https://github.com/imranzahid01/led-clock](https://github.com/imranzahid01/led-clock)

![Screenshot](https://raw.githubusercontent.com/imranzahid01/led-clock/master/screenshot.png)

**Comment by felixhageloh** [comment]
hey, really sorry about this - for some reason I did not see a notification for this. I finally added it to the gallery. It does not show up as a first new widget, because the date order is sorted by the last commit date. If you want you can push a new commit (and ping me here). After I run the build script again it will show up in the front

**Comment by imranzahid01** [comment]
No worries, as long as you have added it :) thanks
