### ISSUE TITLE
Calendar widget: Today view error following upgrade to High Sierra

### ISSUE THREAD

**Issue by krisvibe** [felixhageloh/uebersicht-widgets#335]
As noted - the shadowing/circle for the current date on the calendar widget is erring following the upgrade to High Sierra.  Not sure if it's related to the upgrade or an issue with the widget.  Screenshot attached - see October 2nd

![screen shot 2017-10-02 at 8 23 33 am](https://user-images.githubusercontent.com/15144699/31077168-87669bd6-a74b-11e7-832b-f65c20227885.png)

**Comment by abhivanarase** [comment]
the fix is the following:
`sundayFirstCalendar = 'cal -h && date "+%-m %-d %y"'`
and 
`mondayFirstCalendar =  'cal -h | awk \'{ print " "$0; getline; print "Mo Tu We Th Fr Sa Su"; \
getline; if (substr($0,1,2) == " 1") print "                    1 "; \
do { prevline=$0; if (getline == 0) exit; print " " \
substr(prevline,4,17) " " substr($0,1,2) " "; } while (1) }\' && date "+%-m %-d %y"'`

**Comment by krisvibe** [comment]
Excellent - thank you for the fix!

**Comment by deangwilcox** [comment]
Ditto what krisvibe said! Thank you!

**Comment by 752199526** [comment]
This problem can be fixed in this way; however, when I downloaded the latest version from Übersicht Widgets webpage, the code is not be updated.
<img width="1312" alt="screen shot 2017-10-08 at 20 01 04" src="https://user-images.githubusercontent.com/25854424/31322825-eb93588e-ac63-11e7-84ba-14fd6ffe5dbc.png">

**Comment by felixhageloh** [comment]
The latest version on the gallery should also work again (although with a slightly different fix)
