### ISSUE TITLE
Today Display

### ISSUE THREAD

**Issue by 752199526** [felixhageloh/uebersicht-widgets#347]
This phenomenon happens for several days, could you please tell me what's wrong with the widget?
[
<img width="215" alt="screen shot 2017-11-05 at 16 00 29" src="https://user-images.githubusercontent.com/25854424/32419628-8a02eda6-c242-11e7-80a6-6422be89c2ff.png">
](url)

**Comment by DinoAlbatross** [comment]
I'm having a problem with this too, it seems to vary by week and not by day for me. I'm not good at coding, but I'll poke around a bit, I'll keep you updated.

**Comment by DinoAlbatross** [comment]
I've had a look, and I have a slight hunch that the issue lies somewhere in the bottom half (lines 62 to 120). As I said before, I'm not good at coding. Therefore, I can't understand much of the code. Hopefully, someone with coding experience sees this and figures out a fix. Sorry i couldn't be of more help.

**Comment by DrewKimeAXS** [comment]
I'm seeing this also. 

![screen shot 2017-12-01 at 2 03 07 pm](https://user-images.githubusercontent.com/20602988/33498729-7306d726-d6a0-11e7-9099-61fc54bfc8dd.png)

**Comment by felixhageloh** [comment]
There is a new version in the gallery with a fix!

**Comment by DrewKimeAXS** [comment]
That's got it, thanks!
