### ISSUE TITLE
Stock Quotes Widget updated since Yahoo Stock API got deprecated

### ISSUE THREAD

**Issue by edasque** [felixhageloh/uebersicht-widgets#350]
Moved to another API with better results.

https://github.com/edasque/Stock-quotes-Widget

**Comment by edasque** [comment]
@felixhageloh ping

**Comment by felixhageloh** [comment]
Hey sorry for the late reply - GitHub notifications have been ending up in my spam folder since October. Fixed the issue now, but have lots of things to catch up.

The gallery points directly to your repo, so updates you do there should make it straight through (expect changes to the widget manifest). Let me know if that is not the case!
