### ISSUE TITLE
New widget: Ironman Reactor Widget

### ISSUE THREAD

**Issue by ghost** [felixhageloh/uebersicht-widgets#502]
Please add this widget to the gallery: https://github.com/leejongyoung/ironman-reactor-ubersicht-widget

**Comment by felixhageloh** [comment]
nice looking widget! I am running into an issue because another widget with the exact same repo name already exists (the widget id is based on the repo name at the moment). I can adjust the script to improve that, but not sure how long it will take. If you are willing to use a different repo name you can probably have this added sooner

**Comment by ghost** [comment]
Don't worry, I'll post it again under a different name
Thanks for your activity 😃

**Comment by ghost** [comment]
[https://github.com/leejongyoung/ironman-reactor2-ubersicht-widget](https://github.com/leejongyoung/ironman-reactor2-ubersicht-widget)
I changed the name to Reactor 2.
I'll optimize the code when I have time
I'll make and upload a cooler widget that fits with the Reactor. 🤖

**Comment by felixhageloh** [comment]
great, thank you! I've added it Looking forward to more widgets :)
