### ISSUE TITLE
New widget: Animus Calendar

### ISSUE THREAD

**Issue by thisanimus** [felixhageloh/uebersicht-widgets#515]
Please add this widget to the gallery: https://github.com/thisanimus/ubersicht-calendar

Ever since upgrading to Big Sur, I've been having trouble using Ubersicht widgets that rely on macOS system utilites as a data source. Because of this, I decided to make a calendar widget that relies only on JS.

**Comment by felixhageloh** [comment]
Hi there, first of all sorry for the late reply and thanks for sharing your widget. Is there a chance you can use a different name for your repo since `ubersicht-calendar` is already taken (the id is based on the repo name)?

Also, system commands should be working fine with Big Sur. Did you already file an issue for it?
